require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.2.2
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'scripts/**/*'

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false
